<?php

return [
    [
        'name' => 'appurl',
        'title' => '登录接口地址',
        'type' => 'string',
        'group' => '',
        'visible' => '',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '接口地址必须以http://或https://开头，以/结尾',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'appid',
        'title' => 'APPID',
        'type' => 'string',
        'group' => '',
        'visible' => '',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'appkey',
        'title' => 'APPKEY',
        'type' => 'string',
        'group' => '',
        'visible' => '',
        'content' => [],
        'value' => '',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'types',
        'title' => '开启的登录方式',
        'type' => 'checkbox',
        'group' => '',
        'visible' => '',
        'content' => [
            'wx' => '微信',
            'qq' => 'QQ',
            'sina' => '微博',
        ],
        'value' => 'wx,qq,sina',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name'    => 'bindaccount',
        'title'   => '账号绑定',
        'type'    => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value'   => '1',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '是否开启账号绑定，关闭则自动创建账号',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name' => 'rewrite',
        'title' => '伪静态',
        'type' => 'array',
        'content' => [],
        'value' => [
            'index/index' => '/clogin$',
            'index/connect' => '/clogin/connect/[:type]',
            'index/callback' => '/clogin/callback/[:type]',
            'index/bind' => '/clogin/bind/[:type]',
            'index/unbind' => '/clogin/unbind/[:type]',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
